name: Publish new version of ActivityRegistrator.Models library nuget

on:
  push:
    branches:
    - master
    paths:
    - ActivityRegistrator.Models/**
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      packages: write # Required for writing to the github packages
      contents: read # Required to checkout code
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1

    - name: Build
      run: dotnet build ActivityRegistrator.Models/ActivityRegistrator.Models.csproj --configuration Release

    - name: Pack nugets
      run: dotnet pack ActivityRegistrator.Models/ActivityRegistrator.Models.csproj --configuration Release --no-build --output .

    - name: Publish to GitHub Packages
      run: dotnet nuget push '**/*.nupkg' --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key "${{ secrets.GITHUB_TOKEN }}"
